data:
#  root_dir: ./data/signatures
  root_dir: ./data/ChiSig
  test_root_dir: ./data/test
  data_type: chisig  # 或 cedar
model:
  backbone: signet  # 可选: signet, resnet18
  embedding_dim: 128

train:
  loss_type: hybrid_triplet  # 可选: semi_hard_triplet, triplet, contrastive,hybrid_triplet,batch_hard_triplet
  batch_size: 32
  epochs: 30
  learning_rate: 0.0001
  iterations_per_epoch: 100
  print_interval: 10
  save_interval: 10
  checkpoint_dir: ./checkpoints
  margin: 0.3
eval:
  test: ./output/test
  val: ./output/val
  train: ./output/train